# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Dr. Orhan Kaplan | Data Science Consulting"
email: orhankaplan@gantep.edu.tr
description: "Welcome to my portfolio. I am Dr. Orhan Kaplan, a Senior Data Scientist, Researcher, and Mathematician specializing in translating complex data into high-ROI business solutions. My expertise lies at the intersection of advanced predictive modeling, causal inference, and machine learning operations."
github_username: nalpako2027
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
repository: "nalpako2027/nalpako2027.github.io"
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://wikipedia.org

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Orhan Kaplan, PhD"
  avatar : "/assets/images/bio_photo.jpg"
  bio    : "I am available for independent consulting engagements, freelance contract projects, and dedicated senior data scientist roles"
author:
  name   : "Orhan Kaplan, PhD"
  avatar : "/assets/images/bio_photo.jpg"
  bio    : "I am actively available for independent consulting engagements, freelance contract projects, and dedicated data science roles."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/orhan-kaplan-phd-5a4a84212/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nalpako2027?tab=repositories"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=1q5Kk4UAAAAJ&view_op=list_works&gmla=AO4B3juOxUjKIjKr3K2rC-U5QK2fUhKSEjeE1tM14_9Ct6Hn3Uh8zUCmcx42yVCKhlqX2o1e4N4dOGEd7MMWPVDe"
    - label: "Upwork"
      icon: "fas fa-fw fa-briefcase"
      url: "https://www.upwork.com/freelancers/~01a77d224509343131"


footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_excerpts: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
